name: globalId

on:
  push:
    branches:
      - globalid-release
      - feat-*
    tags:
      - v*

  pull_request:
    branches:
      - globalid-release

jobs:
  build-and-release:
    name: Build docker image
    runs-on: ubuntu-20.04
    env:
      ECR_REGISTRY: 715299534867.dkr.ecr.us-east-1.amazonaws.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.ECR_REGISTRY }}/base/aries-cloudagent
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha,format=long,prefix=
      - name: Login to AWS ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile.globalid
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
